### ISSUE TITLE
blob_type_num is not defined

### ISSUE THREAD

**Issue by BlankerL** [MoneroOcean/xmr-node-proxy#121]
Hello, after updating from v0.17.0 to the latest commit [`07cf7b7`](https://github.com/MoneroOcean/xmr-node-proxy/commit/07cf7b738e7f527a1c73540c22c68fdc6f97bec8), the proxy keeps showing the following content,
```
1|proxy  | 2020-03-08 14:18:29:987 +00:00: ReferenceError: blob_type_num is not defined
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at constructNewBlob (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:40:22)
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at Object.processShare (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:408:37)
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at handleMinerData (/home/nodeproxy/xmr-node-proxy/proxy.js:1250:49)
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at handleMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:1501:13)
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at TLSSocket.<anonymous> (/home/nodeproxy/xmr-node-proxy/proxy.js:1553:25)
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at emitOne (events.js:116:13)
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at TLSSocket.emit (events.js:211:7)
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at addChunk (_stream_readable.js:263:12)
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at readableAddChunk (_stream_readable.js:246:13)
1|proxy  | 2020-03-08 14:18:29:987 +00:00:     at TLSSocket.Readable.push (_stream_readable.js:208:10)
1|proxy  | 2020-03-08 14:18:29:997 +00:00: Worker 68357 died with code: 1, and signal: null
```

All the submissions will not go to the mining pool.

**Comment by BlankerL** [comment]
Revert back to v0.17.0 and everything works fine now, maybe the current version is under development and not ready for production.

**Comment by MoneroOcean** [comment]
Thank for report! I've just fixed this. Can you please check?

**Comment by BlankerL** [comment]
> Thank for report! I've just fixed this. Can you please check?

It is working properly right now. Thank you so much!  I will report here if any bugs persist.
